name: BeastGPT Shorts Streamer

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Weapons
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb ffmpeg build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb -y

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Bot Modules
        run: |
          npm init -y
          npm install canvas mineflayer prismarine-viewer

      - name: Execute BeastGPT Audio-Video Stream Protocol
        env:
          YOUTUBE_KEY: ${{ secrets.YOUTUBE_KEY }}
        run: |
          if [ -z "$YOUTUBE_KEY" ]; then
            echo "🔥 FATAL ERROR: YOUTUBE_KEY is missing!"
            exit 1
          fi
          chmod +x stream.sh
          ./stream.sh
